### ISSUE TITLE
Linux femzip lib exec rights

### ISSUE THREAD

**Issue by steffenslavetinsky** [lasso-gmbh/lasso-python#11]
We installed the latest release (1.5.0) on Ubuntu 20.04 and 18.04 with Python 3.8 and noted a strange behaviour regarding the femzip package.

After Installation, the library access rights are as follows
```
❯ ls -lh
total 92M
-rw-rw-r-- 1 steffen steffen  19K Jan 21 17:11 api_extended.dll
-rw-rw-r-- 1 steffen steffen  34K Jan 21 17:11 api_extended.so
-rw-rw-r-- 1 steffen steffen  21M Jan 21 17:11 femzip_a_dyna_sidact_generic.dll
-rw-rw-r-- 1 steffen steffen  46K Jan 21 17:11 femzip_api.py
-rw-rw-r-- 1 steffen steffen 5,5K Jan 21 17:11 fz_config.py
-rw-rw-r-- 1 steffen steffen   35 Jan 21 17:11 __init__.py
-rw-rw-r-- 1 steffen steffen  27M Jan 21 17:11 libfemzip_a_dyna_sidact_generic.so
-rw-rw-r-- 1 steffen steffen 1,7M Jan 21 17:11 libfemzip_post_licgenerator_ext_flexlm.dll
-rw-rw-r-- 1 steffen steffen 1,3M Jan 21 17:11 libfemzip_post_licgenerator_ext_flexlm.so
-rw-rw-r-- 1 steffen steffen 1,7M Jan 21 17:11 libifcoremd.dll
-rw-rw-r-- 1 steffen steffen 347K Jan 21 17:11 libifportmd.dll
-rw-rw-r-- 1 steffen steffen 3,9M Jan 21 17:11 libimf.so
-rw-rw-r-- 1 steffen steffen 476K Jan 21 17:11 libintlc.so.5
-rw-rw-r-- 1 steffen steffen 1,9M Jan 21 17:11 libiomp5md.dll
-rw-rw-r-- 1 steffen steffen 2,1M Jan 21 17:11 libiomp5.so
-rw-rw-r-- 1 steffen steffen 1,6M Jan 21 17:11 libirng.so
-rw-rw-r-- 1 steffen steffen 4,1M Jan 21 17:11 libmmd.dll
-rw-rw-r-- 1 steffen steffen  25M Jan 21 17:11 libsvml.so
drwxrwxr-x 2 steffen steffen 4,0K Jan 21 17:11 __pycache__
```

but when we try to load a file the access rights are changed and the library aborts with an error:

```
RuntimeError: Library '.....venv/lib/python3.8/site-packages/lasso/femzip/libfemzip_a_dyna_sidact_generic.so' is not executable can couldn't change execution rights.
```

and the libs access rights are as follows

```
❯ ls -lh 
total 92M
-rw-rw-r-- 1 steffen steffen  19K Jan 21 17:11 api_extended.dll
-rw-rw-r-- 1 steffen steffen  34K Jan 21 17:11 api_extended.so
-rw-rw-r-- 1 steffen steffen  21M Jan 21 17:11 femzip_a_dyna_sidact_generic.dll
-rw-rw-r-- 1 steffen steffen  46K Jan 21 17:18 femzip_api.py
-rw-rw-r-- 1 steffen steffen 5,5K Jan 21 17:11 fz_config.py
-rw-rw-r-- 1 steffen steffen   35 Jan 21 17:11 __init__.py
---------x 1 steffen steffen  27M Jan 21 17:11 libfemzip_a_dyna_sidact_generic.so
-rw-rw-r-- 1 steffen steffen 1,7M Jan 21 17:11 libfemzip_post_licgenerator_ext_flexlm.dll
-rw-rw-r-- 1 steffen steffen 1,3M Jan 21 17:11 libfemzip_post_licgenerator_ext_flexlm.so
-rw-rw-r-- 1 steffen steffen 1,7M Jan 21 17:11 libifcoremd.dll
-rw-rw-r-- 1 steffen steffen 347K Jan 21 17:11 libifportmd.dll
-rw-rw-r-- 1 steffen steffen 3,9M Jan 21 17:11 libimf.so
-rw-rw-r-- 1 steffen steffen 476K Jan 21 17:11 libintlc.so.5
-rw-rw-r-- 1 steffen steffen 1,9M Jan 21 17:11 libiomp5md.dll
-rw-rw-r-- 1 steffen steffen 2,1M Jan 21 17:11 libiomp5.so
-rw-rw-r-- 1 steffen steffen 1,6M Jan 21 17:11 libirng.so
-rw-rw-r-- 1 steffen steffen 4,1M Jan 21 17:11 libmmd.dll
-rw-rw-r-- 1 steffen steffen  25M Jan 21 17:11 libsvml.so
drwxrwxr-x 2 steffen steffen 4,0K Jan 21 17:18 __pycache__
```

we produced the error simply by loading a d3plot from file.
The error occurs for compressed and uncompressed files likewise.

```
Python 3.8.5 (default, Oct 29 2020, 16:01:48) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lasso.dyna import D3plot
>>> data = D3plot("path/to/d3plot")
>>> data.plot()
```

it works, when we comment lines 110-114 in femzip_api.py

**Comment by lasso-codie** [comment]
It is unclear why your system prohibits the execution of the .so file, but you can simply run:

```bash
chmod -R 777 .....venv/lib/python3.8/site-packages/lasso/femzip/
```

to make everything in the directory executable. We will investigate what could be done on our side.

**Comment by lasso-codie** [comment]
Just looked it up and -rw-rw-r-- is automatically set when python bundles the package to a whl. We changed these rights and re-uploaded.

We wanted to detect if the lib is not executable and then change the access rights (if we can). On my windows and linux it works unfortunately fine. Not sure what other value would be reasonable.

**Comment by druzsan** [comment]
On my setup (Ubuntu 18.04, python 3.7, lasso-python 1.5.0.post1) I got the same issue.

As I can see in the [docs](https://docs.python.org/3/library/os.html#os.chmod), `os.chmod` expects other values compared to `os.access`. `os.X_OK` which is set in the line 112 in femzip_api.py will be interpreted as `0o1` and only changes execute flag for other users, but `stat.S_IEXEC` (`0o100`) works fine for me. Or even better `os.chmod(path, os.stat(path).st_mode | stat.S_IEXEC)` what preserves existing permissions.

**Comment by lasso-codie** [comment]
The last one should do really well. Good job 👍

**Comment by shannonjryan** [comment]
I see this issue is closed, but I am experiencing the same error. I've reinstalled the package today, so any recent changes should be included.

My setup is mac os 10.15.7, python 3.8.5, lasso-python 1.5.0.post1

After commenting out lines 110-114 in femzip_api.py as suggested by @steffenslavetinsky I now get the following error:

`Exception has occurred: OSError
dlopen(/Users/ryshan/opt/anaconda3/lib/python3.8/site-packages/lasso/femzip/libfemzip_a_dyna_sidact_generic.so, 6): no suitable image found.  Did find:
	/Users/ryshan/opt/anaconda3/lib/python3.8/site-packages/lasso/femzip/libfemzip_a_dyna_sidact_generic.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/ryshan/opt/anaconda3/lib/python3.8/site-packages/lasso/femzip/libfemzip_a_dyna_sidact_generic.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
`
I've had to revert back to version 1.3.1 for the time being.

**Comment by druzsan** [comment]
@shannonjryan that's true, to get fully-working package one should manually change line 112 in femzip_api.py to `os.chmod(path, os.stat(path).st_mode | stat.S_IEXEC)` (potentially right after the installation, before the first run).
@lasso-codie I thought the suggested fix is too small to make a pull request. Should I make one or a package fix/update is under development?

**Comment by lasso-codie** [comment]
The fix will be in the 1.5.0post2 release in the upcoming days.

**Comment by lasso-codie** [comment]
@steffenslavetinsky  In my tests this is not working oddly. I have a .so with "-rwxrwxrwx" and `os.access(path, stat.S_IXUSR)` yields `False`, while `os.access(os.X_OK)` is True.

**Comment by lasso-codie** [comment]
Ok it seems `os.access(os.X_OK)` is the correct test, but `stat.S_IEXEC` should only be used for `os.chmod`

**Comment by druzsan** [comment]
@lasso-codie it seems that `chmod` works in the version 1.5.0.post2, but the next check in the line 113 in `femzip_api.py`
```
if not os.access(path, os.X_OK) or os.access(os.R_OK)
```
misses `path` and thus raises the following exception:
```python
<...>
TypeError: access: path should be string, bytes or os.PathLike, not int
```
So one have to restart code as many times as many dynamic libs there are (and ignore exception every time), then the lasso-python lib is working fine.

---
One possible solution (assumed dynamic libs can be not readable as you mentioned) would be (in `femzip_api.py` again):
```python
111 if not os.access(path, os.X_OK) or not os.access(path, os.R_OK):  # Check r flag here
112     os.chmod(path, os.stat(path).st_mode | stat.S_IEXEC | stat.S_IREAD)  # r flag is adjusted too
113     if not os.access(path, os.X_OK) or not os.access(path, os.R_OK):  # Exactly the same check as in the line 111
                <...>
```

**Comment by lasso-codie** [comment]
I wonder how my tests could not detect this ... This is the hopefully final version. 

```python
    @staticmethod
    def load_dynamic_library(path: str) -> CDLL:
        ''' Load a library and check for correct execution

        Parameters
        ----------
        path: str
            path to the library

        Returns
        -------
        library: CDLL
            loaded library
        '''

        # check executable rights
        if not os.access(path, os.X_OK) or not os.access(path, os.R_OK):
            os.chmod(path, os.stat(path).st_mode | stat.S_IEXEC | stat.S_IREAD)
            if not os.access(path, os.X_OK) or not os.access(path, os.R_OK):
                err_msg = "Library '{0}' is not executable and couldn't change execution rights."
                raise RuntimeError(err_msg.format(path))

        return CDLL(path)
```
