### ISSUE TITLE
Preferred plot package

### ISSUE THREAD

**Issue by sharkweek** [lasso-gmbh/lasso-python#13]
I'm working on further extending the `Binout` class in the `dyna` module to include some embedded plotting methods using `plotly`. I'm wondering if I can submit a pull request for this functionality. Is there a preferred plotting package other than `plotly` or is there any aversion to implementing a specific plotting package in general?

**Comment by tnt-codie** [comment]
PR's are always welcome. Also plotly is fine 👍
