### ISSUE TITLE
Reading ICFD results

### ISSUE THREAD

**Issue by prabhakaran2395** [lasso-gmbh/lasso-python#18]
Is there a way to read the ICFD result files using LASSO ?

**Comment by codie3611** [comment]
Hi @prabhakaran2395 , the library just supports structural mechanics and related solver results such as SPH but no ICFD.

**Comment by prabhakaran2395** [comment]
Thanks @codie3611 for the response. Any suggestions from you to read the d3plot by ourselves. We are facing problems while decoding it.
