### ISSUE TITLE
Array reshape problem

### ISSUE THREAD

**Issue by aftoryte** [lasso-gmbh/lasso-python#2]
Hi! Thanks for the great library ! Keep up the good work! 
After trying to import a d3plot file I have stumbled upon this error :
line 130, in __init__
    self._read_states()
 line 1828, in _read_states
    var_index = self._read_states_beams(state_data, var_index, array_dict)
line 2314, in _read_states_beams
    .reshape((n_states, n_beams, n_layers, 2))
ValueError: cannot reshape array of size 493440 into shape (1542,16,2,2)
Any suggestions ?
Thank you !

**Comment by lasso-codie** [comment]
Seems your model has beam integration points and I messed up somewhere. Do you maybe have a shareable test file?

**Comment by aftoryte** [comment]
Yes the model has beam integration points, but I don't have a model to share right now. I`ll try to make one for you in the next several days. 
Greetings !

**Comment by lasso-codie** [comment]
I created a test file on my own and fixed the bug. It will be done in 1.1.1.
