### ISSUE TITLE
multi-processing support

### ISSUE THREAD

**Issue by jackshen2028** [lasso-gmbh/lasso-python#22]
Dear Developer,

Currently, I am using lasso.dyna to do some post-processing with d3plot result files. I am wondering if lasso-python supports multitread processing during reading d3plot files (~30Gb)? Any suggestions regarding the enhancement of data loading performance are appreciated! Thanks for sharing this wonderful package.

Best regards!
Jack Shen

**Comment by codie3611** [comment]
That would actually not help. The sole and only bottleneck is IO namely pulling memory into RAM. You can reduce the states if you just need e.g. the last one with `state_filter` or if you only like to load specific arrays you can go for `state_array_filter`, which together with `buffered_reading` reduces memory size. For speed though solely `state_filter` will help. The format is pretty screwed up so there is hardly any reasonable optimizations left for the reader at the moment. Namely data is so littered across the files that you can hardly leave parts out.
