### ISSUE TITLE
Not able to read out "bndout -> velocity/rigidbodies"

### ISSUE THREAD

**Issue by Jdahn** [lasso-gmbh/lasso-python#3]
DUPLICATE ISSUE to #65 in qd-cae.

I am using version 1.1.1 of the lasso.dyna package in combination with a R9.3 dyna result container.
It looks like I can not read out the velocity/rigidbodies from the rigid body.

```
>>> Results =  Binout('Simulation.key.binout0000')
>>>print(Results.read('bndout'))
['pressure']
>>>print(Results.read('bndout','velocity/rigidbodies'))
[]
```

If I open the same file using hyperview (2018.3) i see the velocity/rigidbodies option after selecting bndout.
It looks like i can not read out "bndout -> velocity/rigidbodies"

**Comment by lasso-codie** [comment]
Did you search the content somewhere else in the file? If hyperview displays it that way it does not mean that it is stored in that way within the file.

**Comment by Jdahn** [comment]
Yeah I searched the entire content of the binout file but couldn't find reaction forces in rigid bodies / total BC forces.

**Comment by Jdahn** [comment]
Cool that pointed me in the right direction. I thought all following files would be loaded automatically. The second binout file contains the velocities/forces. Thanks!
What whould be the most convenient way to load all binout files and merge the results in one python variable?
