### ISSUE TITLE
Documentation for ArrayTypes

### ISSUE THREAD

**Issue by sgreenhill** [lasso-gmbh/lasso-python#7]
Hi, and many thanks for this library.

I am trying to determine if I can migrate some code from qd-cae to lasso-python.

I need to analyse a solid mesh to determine which nodes are connected. Does lasso-python provide the solid deletion status, neighbouring nodes and material type?

Previously in qd-cae I could use:

```
elem_solid_deletion_info (n_states, n_solids)

elem_solid_data (n_solids x 9)
	# elements [0..7] are the neighbouring node indexes
	# element [8] is the material type
```

These were not in the standard API, but were accessible via the RAW API. Under lasso-python ArrayTypes I can see:

```
element_solid_is_alive (n_states, n_solids)
element_solid_node_indexes (n_solids, 8)
element_solid_part_indexes (n_solids)
```

Do these provide the same information? Does "is_alive" mean "not deleted"?

**Comment by lasso-codie** [comment]
1. You are correct: "is_alive" means "not deleted". It gives you access to the deletion status. 
2. There is no function for neighboring nodes. It is relatively simple though by using `NearestNeighbor` or `KDTree` from [sklearn](https://scikit-learn.org/stable/modules/neighbors.html)
3. Material Type is accessible through `ArrayType.part_material_type` but this array is not always present. You should get the material type by `material_type[part_indexes]`.
