### ISSUE TITLE
some issues with node_displacementes

### ISSUE THREAD

**Issue by jmaestre2** [lasso-gmbh/lasso-python#8]
Hello,

Let me thanks for this wonderful tool. 
Using the code, I think I found a bug related to the d3plot. When I extract the nodal displacement and I compare it with the plot in LS-prepost, the results are completely different. I tried as well with the nodal velocity and acceleration, and they are different. 
Here it is the code I am using:
from lasso.dyna import D3plot, ArrayType
d3plot = D3plot(d3plot)
coordinates=d3plot.arrays["node_coordinates"]
disp = d3plot.arrays["node_displacement"]
vel = d3plot.arrays["node_velocity"]

You can find the dyna files here:
https://cernbox.cern.ch/index.php/s/qw9Ieun6Zwk5lGi

Thanks

**Comment by lasso-codie** [comment]
Which version are you using? It works on my side with 1.3.0. I saw there was temperature in the model and in the newest version was a patch to fix and improve temperature-based results. You can update by:

```bash
python -m pip install --upgrade lasso-python
```

**Comment by jmaestre2** [comment]
Thanks a lot for the quick response.
Yes, I am using that version. In anycase, I have just upgraded it.

Nevertheless, I have the same issue. This is the code I am exactly running:
d3plot = D3plot(d3plotFile)
disp = d3plot.arrays["node_displacement"]

disp[0,0,:]
Out[7]: array([-0.40006179, -0.15507737,  2.6649936 ])

...At the time 0, for the node 0, the displacement is very large when it is
expected to be 0. Actually it seems to be the coordinates of the node.

Thanks a lot!!

**Comment by lasso-codie** [comment]
glad it's fine. The array is definitely mislabeled 😒 I'm open for alternative name suggestions. Unfortunately coordinates already exists, though I thought about renaming coordinates to geometry_coordinates and then maybe displacement to coordinates.

**Comment by jmaestre2** [comment]
...and if you plot the velocity, it is wrong as well...it seems to be the temperature or other variable
vel = d3plot.arrays["node_velocity"]
vel[0,0,:]
Out[9]: array([22., 22., 22.])

Thanks a lot

**Comment by jmaestre2** [comment]
...I think the bug maybe it is related to the pointers or memory position. Acceleration field seems to be not correct also.
