### ISSUE TITLE
some issues with node_displacementes

### ISSUE THREAD

**Issue by jmaestre2** [lasso-gmbh/lasso-python#9]
Please, let me re-open this topic.
I think the problem is not only a mislabeling bug. Having a look to other variables, like velocity, acceleration, it seems the values are not correct neither. Maybe the bug is related to the memory address or pointers.

Thanks for this wonderful tool

**Comment by lasso-codie** [comment]
Can confirm that there is a field switch. Node velocity seems to be temperature.

**Comment by lasso-codie** [comment]
The file specs of d3plot don't indicate the order of node fields. There seems to be a contradiction to previous tests with runs containing temperature, where the temperature was behind acceleration. Atm it is unclear why suddenly temperature is between displacement and velocity.

**Comment by jmaestre2** [comment]
...is it possible that it is due to different lsdyna versions?

Thanks for everything!

**Comment by lasso-codie** [comment]
I found the issue. Was indeed just an ordering issue. Will try to release a fix today.

**Comment by lasso-codie** [comment]
@jmaestre2 has been published you should be able to upgrade now

**Comment by jmaestre2** [comment]
I am glad you are found the issue. 
Thanks a lot!
